# Generated by Django 4.1.2 on 2022-10-25 06:43

from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocKinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=150, unique=True, verbose_name='Виды документов')),
            ],
            options={
                'verbose_name': 'Вид документа',
                'verbose_name_plural': 'Виды документов',
            },
        ),
        migrations.CreateModel(
            name='DocRequisiteTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(max_length=100, unique=True, verbose_name='Тип значения реквизита')),
            ],
            options={
                'verbose_name': 'Тип значения реквизита',
                'verbose_name_plural': 'Типы значений реквизитов',
            },
        ),
        migrations.CreateModel(
            name='DocTemplateRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisite', models.CharField(max_length=150, verbose_name='Реквизит')),
                ('req_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.docrequisitetypes', verbose_name='Тип значения реквизита')),
            ],
            options={
                'verbose_name': 'Реквизит документа',
                'verbose_name_plural': 'Реквизиты документов',
                'unique_together': {('req_type_id', 'requisite')},
            },
        ),
        migrations.CreateModel(
            name='DocTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, unique=True, verbose_name='Тип документа')),
                ('kind', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.dockinds', verbose_name='Вид документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'unique_together': {('kind_id', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DocTypeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150, verbose_name='Категория документа')),
                ('type', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.doctypes', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Категория типа документа',
                'verbose_name_plural': 'Категории типов документов',
                'unique_together': {('type_id', 'category')},
            },
        ),
        migrations.CreateModel(
            name='DocTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(max_length=5000, upload_to=documents.models.DocTemplateUploadPath, verbose_name='Шаблон документа')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.doctypecategories', verbose_name='Категория типа документа')),
                ('requisites', models.ManyToManyField(to='documents.doctemplaterequisites', verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.CreateModel(
            name='DocTemplatePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=300, verbose_name='Пункт шаблона')),
                ('tag', models.CharField(max_length=50, verbose_name='Тэг пункта шаблона')),
                ('template', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.doctemplates', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пункт шаблона документа',
                'verbose_name_plural': 'Пункты шаблонов документов',
            },
        ),
    ]
