# Generated by Django 4.1.2 on 2022-10-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctypes',
            name='type',
            field=models.CharField(max_length=150, verbose_name='Тип документа'),
        ),
    ]
