# Generated by Django 4.1.2 on 2022-10-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_doctypes_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctemplatepoints',
            unique_together={('template', 'tag')},
        ),
    ]
