# Generated by Django 4.1.2 on 2022-11-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_doctemplatepoints_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitePossibleValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_value', models.CharField(max_length=200, verbose_name='Возможное значение')),
                ('requisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.doctemplaterequisites', verbose_name='Реквизит')),
            ],
            options={
                'verbose_name': 'Возможное значение реквизита',
                'verbose_name_plural': 'Возможные значения реквизитов',
                'unique_together': {('requisite_id', 'possible_value')},
            },
        ),
    ]
