# Generated by Django 4.1.2 on 2022-11-04 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_requisitepossiblevalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctemplates',
            name='date_create',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания шаблона'),
        ),
        migrations.AddField(
            model_name='doctemplates',
            name='name',
            field=models.CharField(default='Шаблон', max_length=250, verbose_name='Наименование шаблон'),
        ),
    ]
