# Generated by Django 4.1.2 on 2022-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_doctemplaterequisites_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctemplaterequisites',
            name='tag',
            field=models.CharField(default='tag', max_length=30, unique=True, verbose_name='Тэг'),
        ),
    ]
