# Generated by Django 4.1.2 on 2022-11-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_doctemplaterequisites_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctemplaterequisites',
            name='tag',
            field=models.CharField(default='tag', max_length=30, verbose_name='Тэг'),
        ),
    ]
