# Generated by Django 4.1.2 on 2022-11-08 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_doctemplaterequisites_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctemplates',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания шаблона'),
        ),
    ]
