# Generated by Django 4.1.2 on 2022-10-27 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=250, verbose_name='Отчество')),
                ('phone', models.PositiveIntegerField(verbose_name='Номер телефона')),
                ('djuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='djuser')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
