# Generated by Django 4.1.2 on 2022-10-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='department',
            field=models.CharField(default='', max_length=1000, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='position',
            field=models.CharField(default='', max_length=250, verbose_name='Должность'),
        ),
    ]
