# Generated by Django 4.1.2 on 2022-10-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_profiles_department_profiles_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='department',
            field=models.CharField(default='', max_length=1000, null=True, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='position',
            field=models.CharField(default='', max_length=250, null=True, verbose_name='Должность'),
        ),
    ]
